/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2021-09-07 12:54:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("  <head>\n");
      out.write("    <title>DirEngine - Free Bootstrap 4 Template by Colorlib</title>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("    \n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Alex+Brush\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/open-iconic-bootstrap.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/animate.css\">\n");
      out.write("    \n");
      out.write("    <link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/owl.theme.default.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/magnific-popup.css\">\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/aos.css\">\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/ionicons.min.css\">\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap-datepicker.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/jquery.timepicker.css\">\n");
      out.write("\n");
      out.write("    \n");
      out.write("    <link rel=\"stylesheet\" href=\"css/flaticon.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/icomoon.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("\n");
      out.write("      <nav class=\"navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light\" id=\"ftco-navbar\">\n");
      out.write("          <div class=\"container\">\n");
      out.write("              <a class=\"navbar-brand\" href=\"index.html\"><img src=\"images/logo2.png\" width=\"40px\" height=\"40px\"> Easy Travel</a>\n");
      out.write("              <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#ftco-nav\" aria-controls=\"ftco-nav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("                  <span class=\"oi oi-menu\"></span> Menu\n");
      out.write("              </button>\n");
      out.write("\n");
      out.write("              <div class=\"collapse navbar-collapse\" id=\"ftco-nav\">\n");
      out.write("                  <ul class=\"navbar-nav ml-auto\">\n");
      out.write("                      <li class=\"nav-item\"><a href=\"index.html\" class=\"nav-link\">首頁</a></li>\n");
      out.write("                      <li class=\"nav-item\"><a href=\"about.html\" class=\"nav-link\">會員中心</a></li>\n");
      out.write("                      <li class=\"nav-item \"><a href=\"tour.html\" class=\"nav-link\">景點</a></li>\n");
      out.write("                      <li class=\"nav-item\"><a href=\"hotel.html\" class=\"nav-link\">住宿</a></li>\n");
      out.write("                      <li class=\"nav-item\"><a href=\"blog.html\" class=\"nav-link\">餐廳</a></li>\n");
      out.write("                      <li class=\"nav-item\"><a href=\"contact.html\" class=\"nav-link\">聯系我們</a></li>\n");
      out.write("                      <li class=\"nav-item cta\"><a href=\"contact.html\" class=\"nav-link\"><span>開始規劃</span></a></li>\n");
      out.write("                  </ul>\n");
      out.write("              </div>\n");
      out.write("          </div>\n");
      out.write("      </nav>\n");
      out.write("      \n");
      out.write("      <!-- END nav -->\n");
      out.write("\n");
      out.write("      <div class=\"hero-wrap js-fullheight\" style=\"background-image: url('images/bg_5.jpg');\">\n");
      out.write("          <div class=\"overlay\"></div>\n");
      out.write("          <div class=\"container\">\n");
      out.write("              <div class=\"row no-gutters slider-text js-fullheight align-items-center justify-content-center\" data-scrollax-parent=\"true\">\n");
      out.write("                  <div class=\"col-md-9 ftco-animate text-center\" data-scrollax=\" properties: { translateY: '70%' }\">\n");
      out.write("\n");
      out.write("                      <h1 class=\"mb-3 bread\" data-scrollax=\"properties: { translateY: '30%', opacity: 1.6 }\">註冊表單</h1>\n");
      out.write("                  </div>\n");
      out.write("              </div>\n");
      out.write("          </div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("      <section class=\"ftco-section ftco-degree-bg\">\n");
      out.write("          <div class=\"container\">\n");
      out.write("\n");
      out.write("              <div class=\"col-lg-10\">\n");
      out.write("                  <div class=\"row\">\n");
      out.write("\n");
      out.write("                      <div class=\"col-md-12 hotel-single ftco-animate mb-5 mt-4\">\n");
      out.write("\n");
      out.write("                          <h4 class=\"mb-5\">註冊畫面 </h4>\n");
      out.write("                          <form method=\"post\" action=\"RegisterCheck.controller\" enctype=\"multipart/form-data\" >\n");
      out.write("\n");
      out.write("                              <div class=\"row align-items-end\">\n");
      out.write("                                  <div class=\"col-md-6\">\n");
      out.write("                                      <div class=\"form-group\">\n");
      out.write("                                         \n");
      out.write("                                          <input class=\"form-control\" type=\"text\" name=\"username\" id=\"username\" placeholder=\"請輸入帳號\" value=\"\" />\n");
      out.write("                                      </div>\n");
      out.write("                                  </div>\n");
      out.write("                                  <div class=\"col-md-6\">\n");
      out.write("                                      <div class=\"form-group\">\n");
      out.write("                                        \t<lable for=\"password\">密碼</lable>\n");
      out.write("                                          <input class=\"form-control\" type=\"password\" name=\"password\" id=\"password\" placeholder=\"請輸入密碼\" value=\"\" />\n");
      out.write("                                      </div>\n");
      out.write("                                  </div>\n");
      out.write("                                  \n");
      out.write("                                  \n");
      out.write("                                  <div class=\"col-md-6\">\n");
      out.write("                                      <div class=\"form-group\">\n");
      out.write("                                          <lable for=\"name\">姓名</lable>\n");
      out.write("                                          <input class=\"form-control\" type=\"text\" name=\"name\" id=\"name\" placeholder=\"請輸入姓名\" value=\"\" />\n");
      out.write("                                      </div>\n");
      out.write("                                  </div>\n");
      out.write("                                  <div class=\"col-md-6\">\n");
      out.write("                                      <div class=\"form-group\">\n");
      out.write("                                         <lable for=\"password\">身分證字號</lable>\n");
      out.write("                                          <input class=\"form-control\" type=\"text\" name=\"IDName\" id=\"IDName\" placeholder=\"請輸入身分證字號\" value=\"\" />\n");
      out.write("                                      </div>\n");
      out.write("                                  </div>\n");
      out.write("                                  <div class=\"col-md-6\">\n");
      out.write("                                      <div class=\"form-group\">\n");
      out.write("                                          <lable for=\"phoneNumber\">手機號碼</lable>\n");
      out.write("                                          <input class=\"form-control\" type=\"text\" name=\"phoneNumber\" id=\"phoneNumber\" placeholder=\"請輸入手機號碼\" value=\"\" />\n");
      out.write("                                      </div>\n");
      out.write("                                  </div>\n");
      out.write("                                  <div class=\"col-md-6\">\n");
      out.write("                                      <div class=\"form-group\">\n");
      out.write("                                          <lable for=\"address\">聯絡地址</lable>\n");
      out.write("                                          <input class=\"form-control\" type=\"text\" name=\"address\" id=\"address\" placeholder=\"請輸入聯絡地址\" value=\"\" />\n");
      out.write("                                      </div>\n");
      out.write("                                  </div>\n");
      out.write("                                  <div class=\"col-md-6\">\n");
      out.write("                                      <div class=\"form-group\">\n");
      out.write("                                           <lable for=\"email\">電子信箱</lable>\n");
      out.write("                                          <input class=\"form-control\" type=\"text\" name=\"email\" id=\"email\" placeholder=\"請輸入電子信箱\" value=\"\" />\n");
      out.write("                                      </div>\n");
      out.write("                                  </div>\n");
      out.write("\n");
      out.write("                                  <div class=\"col-md-6\">\n");
      out.write("                                      <div class=\"form-group\">\n");
      out.write("                                          <div class=\"select-wrap one-third\">\n");
      out.write("                                              <div class=\"icon\"><span class=\"ion-ios-arrow-down\">請選擇性別</span></div>\n");
      out.write("                                              <select name=\"gender\" id=\"gender\" class=\"form-control\" >\n");
      out.write("\n");
      out.write("                                                  <option value=\"boy\">男生</option>\n");
      out.write("                                                  <option value=\"girl\">女生</option>\n");
      out.write("                                              </select>\n");
      out.write("                                          </div>\n");
      out.write("                                      </div>\n");
      out.write("                                  </div>\n");
      out.write("                                  \t<div class=\"col-md-12\">\n");
      out.write("                                      <div class=\"form-group\">\n");
      out.write("                                  \t\t\t<lable for=\"Birthday\">出生年月日</lable>\n");
      out.write("                                          <input class=\"form-control\" type=\"date\" name=\"Birthday\" id=\"Birthday\" />\n");
      out.write("                                      </div>\n");
      out.write("                                  </div>\n");
      out.write("                                  \n");
      out.write("                                  \n");
      out.write("                                  \n");
      out.write("                                  \n");
      out.write("                                  \n");
      out.write("                                  \n");
      out.write("                                  \n");
      out.write("                                  \n");
      out.write("                                  \n");
      out.write("                                  \n");
      out.write("                                  \n");
      out.write("                                  \n");
      out.write("                                  \n");
      out.write("                                  \n");
      out.write("                                  \n");
      out.write("                                  \n");
      out.write("                                  \n");
      out.write("                                  \n");
      out.write("                                  \n");
      out.write("                                  \n");
      out.write("                                  <div class=\"col-md-12\">\n");
      out.write("                                      <div class=\"form-group\">\n");
      out.write("                                          <input type=\"submit\" value=\"確定並且送出\" class=\"btn btn-primary py-3\">\n");
      out.write("                                      </div>\n");
      out.write("                                  </div>\n");
      out.write("                                  <div class=\"col-md-12\">\n");
      out.write("                                      <div class=\"form-group\">\n");
      out.write("                                          <input type=\"reset\" value=\"取消所有資料\" class=\"btn btn-primary py-3\">\n");
      out.write("                                      </div>\n");
      out.write("                                  </div>\n");
      out.write("                              </div>\n");
      out.write("                          </form>\n");
      out.write("                      </div>\n");
      out.write("                  </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("              </div>\n");
      out.write("          </div> <!-- .col-md-8 -->\n");
      out.write("          \n");
      out.write("      </section> <!-- .section -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("      <!-- .下面是footer -->\n");
      out.write("\n");
      out.write("      <footer class=\"ftco-footer ftco-bg-dark ftco-section\">\n");
      out.write("          <div class=\"container\">\n");
      out.write("              <div class=\"row mb-5\">\n");
      out.write("                  <div class=\"col-md\">\n");
      out.write("                      <div class=\"ftco-footer-widget mb-4\">\n");
      out.write("                          <h2 class=\"ftco-heading-2\">dirEngine</h2>\n");
      out.write("                          <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>\n");
      out.write("                          <ul class=\"ftco-footer-social list-unstyled float-md-left float-lft mt-5\">\n");
      out.write("                              <li class=\"ftco-animate\"><a href=\"#\"><span class=\"icon-twitter\"></span></a></li>\n");
      out.write("                              <li class=\"ftco-animate\"><a href=\"#\"><span class=\"icon-facebook\"></span></a></li>\n");
      out.write("                              <li class=\"ftco-animate\"><a href=\"#\"><span class=\"icon-instagram\"></span></a></li>\n");
      out.write("                          </ul>\n");
      out.write("                      </div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"col-md\">\n");
      out.write("                      <div class=\"ftco-footer-widget mb-4 ml-md-5\">\n");
      out.write("                          <h2 class=\"ftco-heading-2\">Information</h2>\n");
      out.write("                          <ul class=\"list-unstyled\">\n");
      out.write("                              <li><a href=\"#\" class=\"py-2 d-block\">About</a></li>\n");
      out.write("                              <li><a href=\"#\" class=\"py-2 d-block\">Service</a></li>\n");
      out.write("                              <li><a href=\"#\" class=\"py-2 d-block\">Terms and Conditions</a></li>\n");
      out.write("                              <li><a href=\"#\" class=\"py-2 d-block\">Become a partner</a></li>\n");
      out.write("                              <li><a href=\"#\" class=\"py-2 d-block\">Best Price Guarantee</a></li>\n");
      out.write("                              <li><a href=\"#\" class=\"py-2 d-block\">Privacy and Policy</a></li>\n");
      out.write("                          </ul>\n");
      out.write("                      </div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"col-md\">\n");
      out.write("                      <div class=\"ftco-footer-widget mb-4\">\n");
      out.write("                          <h2 class=\"ftco-heading-2\">Customer Support</h2>\n");
      out.write("                          <ul class=\"list-unstyled\">\n");
      out.write("                              <li><a href=\"#\" class=\"py-2 d-block\">FAQ</a></li>\n");
      out.write("                              <li><a href=\"#\" class=\"py-2 d-block\">Payment Option</a></li>\n");
      out.write("                              <li><a href=\"#\" class=\"py-2 d-block\">Booking Tips</a></li>\n");
      out.write("                              <li><a href=\"#\" class=\"py-2 d-block\">How it works</a></li>\n");
      out.write("                              <li><a href=\"#\" class=\"py-2 d-block\">Contact Us</a></li>\n");
      out.write("                          </ul>\n");
      out.write("                      </div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"col-md\">\n");
      out.write("                      <div class=\"ftco-footer-widget mb-4\">\n");
      out.write("                          <h2 class=\"ftco-heading-2\">Have a Questions?</h2>\n");
      out.write("                          <div class=\"block-23 mb-3\">\n");
      out.write("                              <ul>\n");
      out.write("                                  <li><span class=\"icon icon-map-marker\"></span><span class=\"text\">203 Fake St. Mountain View, San Francisco, California, USA</span></li>\n");
      out.write("                                  <li><a href=\"#\"><span class=\"icon icon-phone\"></span><span class=\"text\">+2 392 3929 210</span></a></li>\n");
      out.write("                                  <li><a href=\"#\"><span class=\"icon icon-envelope\"></span><span class=\"text\">info@yourdomain.com</span></a></li>\n");
      out.write("                              </ul>\n");
      out.write("                          </div>\n");
      out.write("                      </div>\n");
      out.write("                  </div>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"row\">\n");
      out.write("                  <div class=\"col-md-12 text-center\">\n");
      out.write("\n");
      out.write("                      <p>\n");
      out.write("                          <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n");
      out.write("                          Copyright &copy;\n");
      out.write("                          <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"icon-heart\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\n");
      out.write("                          <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n");
      out.write("                      </p>\n");
      out.write("                  </div>\n");
      out.write("              </div>\n");
      out.write("          </div>\n");
      out.write("      </footer>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("      <!-- loader -->\n");
      out.write("<!--       <div id=\"ftco-loader\" class=\"show fullscreen\"><svg class=\"circular\" width=\"48px\" height=\"48px\"><circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke=\"#eeeeee\" /><circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#F96D00\" /></svg></div> -->\n");
      out.write("\n");
      out.write("\n");
      out.write("      <script src=\"js/jquery.min.js\"></script>\n");
      out.write("      <script src=\"js/jquery-migrate-3.0.1.min.js\"></script>\n");
      out.write("      <script src=\"js/popper.min.js\"></script>\n");
      out.write("      <script src=\"js/bootstrap.min.js\"></script>\n");
      out.write("      <script src=\"js/jquery.easing.1.3.js\"></script>\n");
      out.write("      <script src=\"js/jquery.waypoints.min.js\"></script>\n");
      out.write("      <script src=\"js/jquery.stellar.min.js\"></script>\n");
      out.write("      <script src=\"js/owl.carousel.min.js\"></script>\n");
      out.write("      <script src=\"js/jquery.magnific-popup.min.js\"></script>\n");
      out.write("      <script src=\"js/aos.js\"></script>\n");
      out.write("      <script src=\"js/jquery.animateNumber.min.js\"></script>\n");
      out.write("      <script src=\"js/bootstrap-datepicker.js\"></script>\n");
      out.write("      <script src=\"js/jquery.timepicker.min.js\"></script>\n");
      out.write("      <script src=\"js/scrollax.min.js\"></script>\n");
      out.write("      <script src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false\"></script>\n");
      out.write("      <script src=\"js/google-map.js\"></script>\n");
      out.write("      <script src=\"js/main.js\"></script>\n");
      out.write("\n");
      out.write("  </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
